name: Build and E2E test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Install packages
        run: |
          yarn install

      - name: Build
        run: |
          yarn build
        env:
          MONGO_URI: mongodb://localhost/nest
          FRONTEND_URL: http://localhost:3000
          SECRET_KEY: your_secret_key_here
          JWT_EXPIRES_IN: 1d

      - name: E2E test
        run: |
          yarn test:e2e
