name: Build and E2E test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Copy .env.sample to .env
        run: |
          cp .env.sample .env

      - name: Install packages
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: E2E test
        run: |
          yarn test:e2e
